export default [
  "Amor",
  "Casa",
  "Cachorro",
  "Felicidade",
  "Livro",
  "Computador",
  "Beleza",
  "Árvore",
  "Chuva",
  "Comida",
  "Tempo",
  "Família",
  "Sorriso",
  "Criança",
  "Mar",
  "Sol",
  "Lua",
  "Estrela",
  "Jardim",
  "Montanha",
  "Cidade",
  "Praia",
  "Coração",
  "Carro",
  "Música",
  "Dança",
  "Arte",
  "Sonho",
  "Viagem",
  "Alegria",
  "Trabalho",
  "Saúde",
  "Escola",
  "Amizade",
  "Festa",
  "Esperança",
  "Riso",
  "Paz",
  "Natureza",
  "Fruta",
  "Flor",
  "Ar",
  "Terra",
  "Rio",
  "Brincadeira",
  "Esporte",
  "Fogo",
  "Neve",
  "Universo",
  "Fantasia",
  "Animal",
  "Cinema",
  "Religião",
  "História",
  "Tecnologia",
  "Cérebro",
  "Sentimento",
  "Medo",
  "Coragem",
  "Energia",
  "Conhecimento",
  "Inspiração",
  "Desafio",
  "Conquista",
  "Simplicidade",
  "Complexidade",
  "Honestidade",
  "Justiça",
  "Libertação",
  "Solidão",
  "Companhia",
  "Conexão",
  "Distância",
  "Proximidade",
  "Aventura",
  "Mistério",
  "Revelação",
  "Aprendizado",
  "Desenvolvimento",
  "Transformação",
  "Rotina",
  "Inovação",
  "Diversão",
  "Descontração",
  "Seriedade",
  "Equilíbrio",
  "Caos",
  "Ordem",
  "Gentileza",
  "Generosidade",
  "Compromisso",
  "Persistência",
  "Resiliência",
  "Vulnerabilidade",
  "Autenticidade",
  "Criatividade",
  "Imaginação",
  "Exploração",
  "Descoberta",
  "Gratidão",
  "Intuição",
  "Aceitação",
  "Diversidade",
  "Rotina diária",
  "Estilo de vida",
  "Hobbies",
  "Moda",
  "Celebridade",
  "Alimentos favoritos",
  "Rotinas de exercícios",
  "Animais de estimação",
  "Lugares favoritos",
  "Série de TV",
  "Filme favorito",
  "Hábitos saudáveis",
  "Hábitos não saudáveis",
  "Tecnologia moderna",
  "Jogos de vídeo",
  "Telefone",
  "Cadeira",
  "Mesa",
  "Óculos",
  "Relógio",
  "Caneta",
  "Lápis",
  "Papel",
  "Bicicleta",
  "Barco",
  "Avião",
  "Cama",
  "Travesseiro",
  "Colcha",
  "Tênis",
  "Camiseta",
  "Calça jeans",
  "Mochila",
  "Bolsa",
  "Óculos de sol",
  "Chave",
  "Lanterna",
  "Facão",
  "Panela",
  "Garfo",
  "Faca",
  "Colher",
  "Prato",
  "Copos",
  "Xícara",
  "Pia",
  "Geladeira",
  "Fogão",
  "Micro-ondas",
  "Tapete",
  "Almofada",
  "Mesa de centro",
  "Sofá",
  "Estante",
  "Luminária",
  "Abajur",
  "Espelho",
  "Cortina",
  "Vaso",
  "Quadro",
  "Escova de dentes",
  "Pasta de dentes",
  "Fio dental",
  "Toalha",
  "Sabonete",
  "Shampoo",
  "Condicionador",
  "Secador de cabelo",
  "Escova de cabelo",
  "Tesoura",
  "Máquina de lavar",
  "Secadora de roupas",
  "Varal",
  "Escova de limpeza",
  "Aspirador de pó",
  "Vassoura",
  "Rodo",
  "Balde",
  "Detergente",
  "Esponja",
  "Pano de limpeza",
  "Lixeira",
  "Saco de lixo",
  "Recipiente de reciclagem",
  "Computador portátil",
  "Tablet",
  "Smartphone",
  "Teclado",
  "Mouse",
  "Monitor",
  "Impressora",
  "Fone de ouvido",
  "Carregador",
  "Cabo USB",
  "Bateria",
  "Carregador portátil"
];
